### ISSUE TITLE
Using Your Code in Appcelerator

### ISSUE THREAD

**Issue by RayKahn** [demonnico/PinterestSwift#14]
Hi there,
I was wondering whether you could provide direction as how to use your transition in Appcelerator. Any guidance would be greatly appreciated.

**Comment by demonnico** [comment]
@RayKahn 
I'm sorry to tell you that this is just a demo project to reply the [question](http://stackoverflow.com/questions/22900499/how-to-transition-from-uicollectionview-to-uiviewcontroller-like-pinterest-evern?noredirect=1#comment38011177_22900499).

If you wanna to implement a similar transaction in your project, maybe this [repository](https://github.com/NewAmsterdamLabs/ZOZolaZoomTransition) will be suitable for you.
