### ISSUE TITLE
滑动到最底部的时候，push 和 pop 后 会出现不完美的显示

### ISSUE THREAD

**Issue by sseen** [demonnico/PinterestSwift#18]
这里有个不完美的展示，如下图。
我发现是由于 NTTansition 这句前后转换坐标的时候，出现不一致的情况，pop 前后取出来的值竟然不一致，具体相差 64 pixel 刚好；如果没有滑到最后，或者多半不会出现这种不一致的情况。
很想知道问题在哪里，还希望花点时间来看下，谢谢😄
`let leftUpperPoint = gridView!.convertPoint(CGPointZero, toView: toViewController.view)`

push 之前
![simulator screen shot 2016 7 11 5 39 33](https://cloud.githubusercontent.com/assets/3367000/16726385/7d18435a-478e-11e6-82c1-ca48fdf2fc2c.png)

pop 之后
![simulator screen shot 2016 7 11 5 39 38](https://cloud.githubusercontent.com/assets/3367000/16726395/8a2bbac2-478e-11e6-94c5-ff09e4f6d001.png)

**Comment by demonnico** [comment]
@sseen 直接clone的项目后跑的吗？没有出现你说的情况唉
