### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by BigBlueHat** [demonnico/PinterestSwift#30]
First, thanks for building this library!

Second, I'm a bit confused about the licensing. The README states that it's [MIT licensed](https://github.com/demonnico/PinterestSwift#license), but the code states that it's "[All Rights Reserved](https://github.com/demonnico/PinterestSwift/blob/master/PinterestSwift/Extension.swift#L6)."

Would it be possible to get the inline code comments updated to reflect the README?

I'd be happy to send a Pull Request that makes the change--if you're OK with the change.

Thanks!
:tophat:

**Comment by BigBlueHat** [comment]
Also, adding the MIT license in a `LICENSE` file in the root of the repository (and possibly in each sub-directory if these can/do get used independently) is important--which I can also provide if you'd like help. :smiley:

Here's the text (would need the copyright line updated): https://choosealicense.com/licenses/mit/

**Comment by demonnico** [comment]
Sorry for late reply, and thanks for your feedback, LICENSE have been updated.
